version: "3.8"

services:
  splunk:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=P@ssw0rd!!!!
    networks:
      - splunk
    restart: always

  nginx:
    image: nginx
    ports:
      - 80:80/tcp
    networks:
      - splunk
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - splunk
    restart: always

networks:
  splunk: