version: "3.8"

services:
  grafana:
    image: grafana/grafana
    networks:
      - grafana

  nginx:
    image: nginx
    ports:
      - 80:80/tcp
    networks:
      - grafana
    volumes:
      - ./grafana.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  grafana: