name: ansible-lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Check Ansible files for errors
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: true